spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/mysqldb?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
decorator:
  datasource:
    p6spy:
      enable-logging: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /lemontree/swagger.html
    disable-swagger-default-url: true
    enabled: true
    display-operation-id: true
  packages-to-scan: com.lemontree.exam
